config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :challenges, :except => [:edit, :update] do
    resources :challenge_infos, only: [:new, :create, :index]
    resources :invites, :only => [:new, :create]
  end
  resources :challenge_infos, only: [:edit, :update] do
    resources :exercise_sessions, only: [:new, :create, :index]
  end
  resources :invites, :only => [:show, :edit, :update]
  resources :exercise_sessions, only: [:show, :destroy, :edit, :update] do
    resources :exercise_comments, only: [:new, :create, :edit, :update]
  end
  resources :exercise_comments, only: [:destroy]
  post "change_status", to: "challenge_infos#change_status", as: :change_status
  get "/challenges/:challenge_id/challenge_infos/top", to: "challenge_infos#top", as: :top
  get "my_friends", to: "exercise_sessions#my_friends", as: :my_friends
  post "like", to: "exercise_sessions#like", as: :like
  get "profile", to: "pages#profile", as: :profile

  resources :users, only: [:index, :show]
  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_list.html.erb
<div >
  <div class="challenges" data-search-challenges-target="list">
  <% if @challenges.any? %>
      <% @challenges.each do |challenge| %>
        <%= render "challenge", challenge: challenge %>
      <% end %>
    <% else %>
      <%= "No challenges" %>
    <% end %>
  </div>
</div>

app/views/shared/_meta_tags.html.erb
<p>todos los metatags</p>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
<div class="row"></div>
  <div class="container-fluid">
  <div class="col-4">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= link_to "BUDD-FIT CHALLENGE", challenges_path, class: "nav-link brand ps-3" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

  </div>
  <div class="col-4">
    <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item">
            <%= link_to "Challenges", challenges_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item">
            <%= link_to "Profile", profile_path, class: "nav-link text-white" %>
          </li>
        <% end %>
      </ul>
    </div>

  </div>
  <div class="col-4">
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link btn btn-warning" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "btn btn-warning" %>
          </li>
          <li class="nav-item">
            <%= link_to "Register", new_user_registration_path, class: "btn btn-outline-light" %>
          </li>
        <% end %>
      </ul>
    </div>

  </div>
  </div>
</div>

app/views/shared/_search.html.erb
<%= simple_form_for :search, url: root_path, method: :get, data: { search_challenges_target:"form"} do |f| %>
  <div class="search-form-control form-group search-module mx-5" id="search-bar">
    <input class="form-control string required" type="text" name="query" id="search_query" placeholder="Search Challenge" data-search-challenges-target="input" data-action="keyup->search-challenges#update"/>
    <button  type="submit" class="btn btn-flat">
      <i class="fas fa-search"></i> Search
    </button>
  </div>
<% end %>

app/views/shared/_spacer.html.erb
<div class="spacer">
  <div></div>
</div>