config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :challenges, :except => [:edit, :update] do
    resources :challenge_infos, only: [:new, :create, :index]
    resources :invites, :only => [:new, :create]
  end
  resources :challenge_infos, only: [:edit, :update] do
    resources :exercise_sessions, only: [:new, :create, :index]
  end
  resources :invites, :only => [:show, :edit, :update]
  resources :exercise_sessions, only: [:show, :destroy, :edit, :update] do
    resources :exercise_comments, only: [:new, :create, :edit, :update]
  end
  resources :exercise_comments, only: [:destroy]
  post "change_status", to: "challenge_infos#change_status", as: :change_status
  get "/challenges/:challenge_id/challenge_infos/top", to: "challenge_infos#top", as: :top
  get "my_friends", to: "exercise_sessions#my_friends", as: :my_friends
  post "like", to: "exercise_sessions#like", as: :like
  get "profile", to: "pages#profile", as: :profile

  resources :users, only: [:index, :show]
  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/pages/home.html.erb
<div>
  <div class="row banner">
    <div id="banner" class="col-4 align-middle banner">
      <h2 id="title-challenge-landing">CHALLENGE</h2>
      <h2>YOUR BUDDIES</h2>
      <P>Get Better Together, Do The Buddfit Challenge</P>
      <%= link_to "Start Challenge", challenges_path, class:"btn btn-warning" %>
    </div>
    <div id="app-title" class="col-4 d-flex justify-content-center">
      <h1>Budd-fit Challenge</h1>
    </div>
    <div class="col-4 d-flex justify-content-end">
      <div class="image-div">
      <h2 id="motivation">HAVE FUN!!</h2>
      <p id="motivation-text">While reaching your <em>best version!</em></p>
        <div id="img" >
          <img src="<%= asset_path('woman2.png') %>"  alt="woman exercising" class="img-position">
        </div>
      </div>
    </div>
  </div>

  <div class="card card-custom" style="margin-top:25px;">
    <div class="card-body d-flex align-middle">
      <p>Exercising with your friends has never been so fun! Invite them to be part of the next challenge.</p>
    <%= link_to "Buddy Up!", challenges_path, class:"btn btn-warning" %>
    </div>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="shadow">
  <div class="row d-flex">
    <div class="col-8 d-flex justify-content-end">
      <div class="w-50">
        <div id="profile-rand" class="d-flex justify-content-center">
          <div class="w-100">
            <h4>@<%= current_user.nickname %></h4>
          </div>
        </div>
        <div class="d-flex justify-content-center align-items-center" style="height:60vh;">
          <% if current_user.photo.attached? %>
            <%= image_tag current_user.photo, size: "500x500", style: "border-radius: 50%; width: 300px; height: 300px;" %>
            <% else %>
            <%= image_tag "avatar.jpg", size: "500x500", style: "border-radius: 50%; width: 500px; height: 500px;" %>
            <% end %>
        </div>
      </div>
      <div>
        <div style="width: 10vw;">
          <h1 style="height: auto; opacity:0.6">My Profile</h1>
        </div>
      </div>
    </div>

    <div class="col-4 d-flex justify-content-end">
      <div class="shaded"></div>
    </div>
  </div>

  <% if @invites.count.positive? %>
  <div class="card-invite">
    <div class="card-body">
      <% @invites.each do |invite| %>
        <div class="my-3 d-flex align-items-center justify-content-between">
          <p class="card-text">
            @<%= "#{invite.inviter.nickname} has invited you to #{invite.challenge.name} Challenge" %>
          </p>
          <div>
            <div style="display: inline-block;">
              <%= simple_form_for invite, url: invite_path(invite) do |f| %>
                <%= f.hidden_field :status, value: "Accepted" %>
                <%= f.submit "Accept", class: "btn btn-outline-light" %>
              <% end %>
            </div>
            <div style="display: inline-block;">
              <%= simple_form_for invite, url: invite_path(invite) do |f| %>
                <%= f.hidden_field :status, value: "Declined" %>
                <%= f.submit "Decline", class: "btn btn-warning" %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <% else  %>
  <div class="card-invite">
    <div class="card-body">
      <div id="profile-rand">
        <h4 class="text-center" style="height: auto;">You have <%= @invites.count %> invites </h4>
      </div>
    </div>
  </div>
  <% end %>
</div>