config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :challenges, :except => [:edit, :update] do
    resources :challenge_infos, only: [:new, :create, :index]
    resources :invites, :only => [:new, :create]
  end
  resources :challenge_infos, only: [:edit, :update] do
    resources :exercise_sessions, only: [:new, :create, :index]
  end
  resources :invites, :only => [:show, :edit, :update]
  resources :exercise_sessions, only: [:show, :destroy, :edit, :update] do
    resources :exercise_comments, only: [:new, :create, :edit, :update]
  end
  resources :exercise_comments, only: [:destroy]
  post "change_status", to: "challenge_infos#change_status", as: :change_status
  get "/challenges/:challenge_id/challenge_infos/top", to: "challenge_infos#top", as: :top
  get "my_friends", to: "exercise_sessions#my_friends", as: :my_friends
  post "like", to: "exercise_sessions#like", as: :like
  get "profile", to: "pages#profile", as: :profile

  resources :users, only: [:index, :show]
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/exercise_session.rb
class ExerciseSession < ApplicationRecord
  belongs_to :challenge_info
  has_many :exercise_comments, dependent: :destroy
  validates :activity, :time_length, :description, presence: true
  #validates :photo, presence: true
  #validates :evidence, uniqueness: true
  has_one_attached :photo
end

app/controllers/exercise_sessions_controller.rb
class ExerciseSessionsController < ApplicationController
  before_action :find_exercise_session, only: [:show, :edit, :update, :destroy]
  before_action :find_challenge_info, only: [:new, :create]

  def index
    @exercise_sessions = policy_scope(ExerciseSession)
  end

  def new
    @exercise_session = ExerciseSession.new
    authorize @exercise_session
  end

  def create
    @exercise_session = ExerciseSession.new(params_exercise_sessions)
    authorize @exercise_session
    @exercise_session.challenge_info = @challenge_info
    if @exercise_session.save!
      @challenge_info.increment_score
      redirect_to exercise_session_path(@exercise_session), notice: 'Exercise session was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @challenge_info = ExerciseSession.find(params[:id])
    @exercise_comment = ExerciseComment.new
    authorize @exercise_session
  end

  def edit
    #@exercise_session = ExerciseSession.new
    authorize @exercise_session
  end

  def update
    #authorize @exercise_session
    #@exercise_session.save!
    #redirect_to challenge_path(@exercise_session.challenge_info.challenge)
    #redirect_to challenge_path(@exercise_session.challenge_info.challenge)
    authorize @exercise_session
    if @exercise_session.update(params_exercise_sessions)
      redirect_to challenge_path(@exercise_session.challenge_info), notice: 'Exercise session was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  #redirect_to challenge_info_exercise_session_path(@challenge_info, @exercise_session), notice: 'Exercise session was successfully updated.'

  def destroy
    @exercise_session.destroy!
    redirect_to challenge_path(@exercise_session.challenge_info.challenge)
    authorize @exercise_session
  end

  private

  def params_exercise_sessions
    params.require(:exercise_session).permit(:activity, :time_length, :evidence, :description, :like, :created_at, :challenge_info_id, :photo)
  end

  def find_challenge_info
    @challenge_info = ChallengeInfo.find(params[:challenge_info_id])
    unless @challenge_info
      redirect_to root_path, alert: "Challenge Info not found."
    end
  end
  def find_exercise_session
    @exercise_session = ExerciseSession.find(params[:id])
  end
end

app/views/exercise_sessions/_index.html.erb
<div class="container p-4 d-flex justify-content-center">
  <div class="shadow-lg border border-light">
    <div class="m-3">
      <h1>Buddies Evidences</h1>
        <%= @challenge_infos.each do |challenge_info| %>
        <p><strong>Activity:</strong> <%= challenge_info.activity %></p>
        <p><strong>Time Length (minutes):</strong> <%= challenge_info.time_length %></p>
        <p><strong>Description:</strong> <%= challenge_info.description %></p>
        <% if challenge_info.photo.attached? %>
          <p><strong>Photo:</strong></p>
          <%= image_tag challenge_info.photo, size: "500x500", style: "width: 200px; height: 200px;" %>
        <% else %>
          <p class="text-danger">No photo available</p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<%= link_to "Edit Exercise Session", edit_exercise_session_path(challenge_info, @exercise_session), class: "btn btn-primary" %>

app/views/exercise_sessions/edit.html.erb
<div class="container p-4 d-flex justify-content-center">
  <div class="shadow-lg border border-light">
    <div class="m-3">
      <h2>Edit your post evidence</h2>
      <%= simple_form_for [@challenge_info, @exercise_session] do |f| %>
        <%= f.input :activity, collection: Challenge::ACTIVITIES, prompt: "Select an activity" %>
        <%= f.input :time_length, label: "Time Length (minutes)", placeholder: "Enter time length" %>
        <%= f.input :description, label: "Description", placeholder: "Enter description" %>
        <%= f.input :photo, as: :file, label: "Photo", required: true %>
        <% if @exercise_session.errors.has_key?(:photo) %>
          <p class="text-danger"><%= @exercise_session.errors[:photo].first %></p>
        <% end %>
        <%= f.button :submit, "Update your post evidence", class: "btn btn-warning" %>
      <% end %>
    </div>
  </div>
</div>

app/views/exercise_sessions/new.html.erb
<div class="container p-4 d-flex justify-content-center">
  <div class="shadow-lg">
    <div class="m-3">
      <h2>Add your evidence</h2>
      <%= simple_form_for [@challenge_info, @exercise_session], url: challenge_info_exercise_sessions_path(@challenge_info) do |f| %>
        <%= f.input :activity, collection: Challenge::ACTIVITIES, prompt: "Select an activity" %>
        <%= f.input :time_length, label: "Time Length (minutes)", placeholder: "Enter time length" %>
        <%= f.input :description, label: "Description", placeholder: "Enter description" %>
        <%= f.input :photo, as: :file, label: "Photo", required: true %>
        <% if @exercise_session.errors.has_key?(:photo) %>
          <p class="text-danger"><%= @exercise_session.errors[:photo].first %></p>
        <% end %>
        <%= f.button :submit, "Create your post evidence", class: "btn btn-warning" %>
      <% end %>
    </div>
  </div>
</div>

app/views/exercise_sessions/show.html.erb
<div class="container">
  <div class="p-4 d-flex justify-content-center">
    <div class="card card-exercise-session-show">
      <div class="card-body">
        <div class="d-flex justify-content-between align-items-start mb-3">
          <div>
            <h2 class="exercise-title text-white"><%= @challenge_info.activity %></h2>
            <h3 class="exercise-subtitle text-white"><%= @challenge_info.time_length %> min</h3>
          </div>
          <div>
            <% if @exercise_session.challenge_info.user.photo.attached? %>
              <%= image_tag @exercise_session.challenge_info.user.photo, size: "200x200", style: "border-radius: 50%; width: 70px; height: 70px;" %>
            <% else %>
              <%= image_tag "avatar.jpg", size: "200x200", style: "border-radius: 50%; width: 70px; height: 70px;" %>
            <% end %>
          </div>
        </div>
        <p class="exercise-description text-white"><%= @challenge_info.description %></p>
      </div>
      <div class="row no-gutters mx-2">
        <div class="col-md-12">
          <% if @challenge_info.photo.attached? %>
            <%= image_tag @challenge_info.photo, class: "exercise-image card-img-top mb-3", style: "height: 300px; object-fit: cover; border-radius: 10px;" %>
          <% else %>
            <div class="exercise-image-placeholder text-center">
              <p class="text-danger mt-3">No photo available</p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-8 text-center">
      <%= link_to "Add comment", new_exercise_session_exercise_comment_path(@exercise_session), class: "btn btn-warning" %>
      <%= link_to "Go back to challenge", challenge_path(@exercise_session.challenge_info.challenge), class: "btn btn-warning" %>
    </div>
  </div>
</div>

  <div class="container mt-4">
    <div class="row justify-content-center">
      <div class="col-md-8" >
        <ul class="list-group comments-list">
          <% @exercise_session.exercise_comments.each do |exercise_comment| %>
            <li class="list-group-item comment-item row d-flex mt-3" id="exercise_comment_comments">
              <div class="col-10">
                <div class="d-flex">
                  <p class="me-3"><strong><%= exercise_comment.user.nickname %></strong></p>
                  <p><%= exercise_comment.comments %></p>
                </div>
              </div>
              <div class="col-2">
                <% if policy(exercise_comment).update? %>
                  <div class="d-flex justify-content-end">
                    <div class="edit-buttons d-flex">
                      <%= link_to "Edit", edit_exercise_session_exercise_comment_path(@exercise_session, exercise_comment), class: "btn btn-warning btn-sm me-3" %>
                      <%= button_to exercise_comment_path(exercise_comment), method: :delete, class: "btn btn-warning btn-sm mr-2", data: { confirm: "Are you sure?" } do %>
                        <i class="fa-solid fa-trash"></i>
                      <% end %>
                    </div>
                  </div>
                <% end %>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
</div>