config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :challenges, :except => [:edit, :update] do
    resources :challenge_infos, only: [:new, :create, :index]
    resources :invites, :only => [:new, :create]
  end
  resources :challenge_infos, only: [:edit, :update] do
    resources :exercise_sessions, only: [:new, :create, :index]
  end
  resources :invites, :only => [:show, :edit, :update]
  resources :exercise_sessions, only: [:show, :destroy, :edit, :update] do
    resources :exercise_comments, only: [:new, :create, :edit, :update]
  end
  resources :exercise_comments, only: [:destroy]
  post "change_status", to: "challenge_infos#change_status", as: :change_status
  get "/challenges/:challenge_id/challenge_infos/top", to: "challenge_infos#top", as: :top
  get "my_friends", to: "exercise_sessions#my_friends", as: :my_friends
  post "like", to: "exercise_sessions#like", as: :like
  get "profile", to: "pages#profile", as: :profile

  resources :users, only: [:index, :show]
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  include PgSearch::Model
  belongs_to :user
  has_many :invites, dependent: :destroy
  has_many :challenge_infos, dependent: :destroy
  has_many :users, through: :challenge_infos

  TYPES = ["Public", "Private"].freeze
  STATUS = ["created", "active", "finished"].freeze
  ACTIVITIES = ["Open", "Swimming", "Running", "Weight Lifting", "Crossfit", "Barre", "Pilates", "Indoor Cycling", "Boxing", "Other"].freeze

  validates :challenge_type, inclusion: { in: TYPES }
  validates :status, inclusion: { in: STATUS }
  validates :activity, inclusion: { in: ACTIVITIES }
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :name, length: { maximum: 15,
    too_long: "%{count} characters is the maximum allowed" }

  pg_search_scope :search_by_name_and_activity,
                  against: [ :name, :activity ],
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController

  before_action :find_challenge, only: [:show, :destroy, :top]
  before_action :set_admin, only: [:show]

  def index
    @challenges = policy_scope(Challenge)
    if params[:query].present?
      @challenges = Challenge.search_by_name_and_activity(params[:query])
    else
      @challenges = Challenge.all
    end
    @exercise_sessions = ExerciseSession.all.order("RANDOM()").take(14)
    respond_to do |format|
      format.html
      format.text { render partial: "shared/list", locals: {challenges: @challenges}, formats: [:html]}
    end
  end

  def show;
    @invite = Invite.new
    authorize @challenge
    authorize @invite
    @exercise_sessions = ExerciseSession.joins(challenge_info: :challenge).where(challenge_infos: { challenge_id: @challenge.id })
    @user_challenge_info = @challenge.challenge_infos.find_by(user: current_user)
    @cuser_evidence= @challenge.challenge_infos.where(user: current_user).map(&:exercise_sessions).last.last
  end

  def new
    @challenge = Challenge.new
    authorize @challenge
  end

  def create
    @challenge = Challenge.new(params_challenge)
    @challenge.user = current_user
    if @challenge.save!
      ChallengeInfo.create!(
        user: current_user,
        challenge: @challenge
      )
      redirect_to challenge_path(@challenge)
    else
      render new:, status: :unprocessable_entity
    end
    authorize @challenge
  end

  def destroy
    authorize @challenge
    @challenge.destroy!
    redirect_to root_path, status: :see_other
  end
  #>>>>>>>>>>>>>>>>
  # def challenge_status
  # if Date.today == @challenge.start_date.value
  # @challenge.status = "started"
  # elsif @Date.today == @challenge.end_date.value
  # @challenge.status = "finished"
  # end
  #   end
  #>>>>>>>>>>>>>>>>>>>>>>

  private

  # def start
  #   @challenge = Challenge.find(params[:id])
  #   @challenge.
  # end

  def params_challenge
    params.require(:challenge).permit(:name, :duration, :challenge_type, :activity, :status, :global_score, :user_id, :start_date, :end_date)
  end
  def find_challenge
    @challenge = Challenge.find(params[:id])
  end

  def set_admin
    @admin = User.find(@challenge.user_id)
  end
end

app/views/challenges/_buddies-card.html.erb
<div class="buddies-card my-5" style="width: 35rem;">
    <div class="buddies-card-title">
      <h2 id="buddies">BUDDIES</h2>
    </div>
    <div class="row buddies">
      <% @challenge.challenge_infos.where(user_status: "active").each do |challenge_info| %>
        <div class="col-md-3">
          <div class="card-body p-3">
            <div class="avatar-container">
              <%= cl_image_tag challenge_info.user.photo.key, class: "avatar rounded-circle", id: "img-card", data: { score: challenge_info.user_score } %>
              <div class="avatar-overlay">
                <span class="score"><%= challenge_info.user_score %></span>
              </div>
            </div>
            <div class="buddies-card-text text-center">
              <p><%= challenge_info.user.nickname %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/challenges/_button.html.erb
<div>
  <button type="button" class="btn btn-outline-light">Login</button>
  <button type="button" class="btn btn-warning">Register</button>
</div>

app/views/challenges/_card.html.erb
<div class="card-challenge">
  <div class="card-challenge-infos">
    <div class="card-challenge-title">
      <h2 class="card-challenge-name"><%= @challenge.name %></h2>
      <div class="card-challenge-attributes">
        <h3><%= @challenge.activity %></h3>
      </div>
      <div id="card-challenge-days">
      <div class="card-challenge-dates">
        <p>Starts</p>
        <p><%= @challenge.start_date %></p>
      </div>
      <div class="card-challenge-dates">
        <p>Ends</p>
        <p><%= @challenge.end_date %></p>
      </div>
      </div>

    </div>
    <div id="icon" class="d-flex justify-content-center align-middle">
    <% if @challenge.activity == "Barre"%>
  <img src="<%= asset_path('ballet.png') %>"  alt="women doing Barre pose">
  <% elsif @challenge.activity == "Boxing" %>
  <img src="<%= asset_path('boxing.png') %>"  alt="Woman jumping rope">
  <% elsif @challenge.activity == "Weight Lifting" %>
  <img src="<%= asset_path('weightlift.png') %>"  alt="woman exercising">
  <% elsif @challenge.activity == "Pilates" %>
  <img src="<%= asset_path('pilates-ball.png') %>"  alt="woman exercising">
  <% elsif @challenge.activity == "Crossfit" %>
  <img src="<%= asset_path('weightlift.png') %>"  alt="woman exercising">
  <% elsif @challenge.activity == "Running" %>
  <img src="<%= asset_path('run.png') %>"  alt="woman exercising">
  <% elsif @challenge.activity == "Indoor Cycling" %>
  <img src="<%= asset_path('cycling.png') %>"  alt="woman exercising">
  <% elsif @challenge.activity == "Swimming" %>
  <img src="<%= asset_path('swimmer.png') %>"  alt="woman exercising">
  <% elsif @challenge.activity == "Open" %>
  <img src="<%= asset_path('meditation.png') %>"  alt="woman exercising">
  <% end %>
  </div>
    <div class="card-challenge-info">
      <div class="card-challenge-duration">
        <% final = @challenge.end_date.split("-").map(&:to_i) %>
        <% start = @challenge.start_date.split("-").map(&:to_i) %>
        <% duration = (Date.new(final[0],final[1],final[2])-Date.new(start[0],start[1],start[2])).to_i %>
        <h2 id="card-challenge-number"><%= duration %></h2>
        <p>days</p>
      </div>

    </div>
  </div>
    <div class="delete-button">
      <%= button_to "Delete", challenge_path(@challenge), class: "btn btn-warning", method: :delete if policy(@challenge).destroy? %>

    </div>
</div>

app/views/challenges/_challenge-card.html.erb
<div class="card-product create-card card-product-challenge">
  <div class="card-product-infos">
    <h2>Start your own challenge!</h2>
    <%= link_to "Create challenge", new_challenge_path, class: "btn btn-warning" %>
  </div>
</div>

app/views/challenges/_challenge-evidence.html.erb
<div class="card-trip">
  <div class="card-trip-infos">
    <div>
      <h2><%= link_to "#{session.activity}", exercise_session_path(session), class:"show-session" %></h2>
      <h3><%= session.time_length %> mins</h3>
    </div>
    <%= cl_image_tag session.challenge_info.user.photo.key, class:"card-trip-user avatar-bordered"%>
  </div>
  <%= cl_image_tag session.photo.key, class:"img-evidence"%>
</div>

app/views/challenges/_challenge.html.erb
<div class="card-product">
  <% if challenge.activity == "Barre"%>
  <img src="<%= asset_path('Barre2.jpg') %>"  alt="women doing Barre pose">
  <% elsif challenge.activity == "Boxing" %>
  <img src="<%= asset_path('Boxing.jpg') %>"  alt="Woman jumping rope">
  <% elsif challenge.activity == "Weight Lifting" %>
  <img src="<%= asset_path('Weightlifting.jpg') %>"  alt="woman exercising">
  <% elsif challenge.activity == "Pilates" %>
  <img src="<%= asset_path('Pilates2.jpg') %>"  alt="woman exercising">
  <% elsif challenge.activity == "Crossfit" %>
  <img src="<%= asset_path('Crossfit.jpg') %>"  alt="woman exercising">
  <% elsif challenge.activity == "Running" %>
  <img src="<%= asset_path('Running.jpg') %>"  alt="woman exercising">
  <% elsif challenge.activity == "Indoor Cycling" %>
  <img src="<%= asset_path('Cycling.jpg') %>"  alt="woman exercising">
  <% elsif challenge.activity == "Swimming" %>
  <img src="<%= asset_path('Swimming2.jpg') %>"  alt="woman exercising">
  <% elsif challenge.activity == "Open" %>
  <img src="<%= asset_path('Open.jpg') %>"  alt="woman exercising">
  <% end %>
  <div class="card-product-infos">
    <div class="name">
      <h2><%= challenge.name %> Challenge</h2>
    </div>
    <div class="info">
      <div class="attributes">
        <h3><%= challenge.activity %></h3>
        <h3><%= challenge.status %></h3>
      </div>
      <div class="duration">
      <% final = challenge.end_date.split("-").map(&:to_i) %>
    <% start = challenge.start_date.split("-").map(&:to_i) %>
    <% duration = (Date.new(final[0],final[1],final[2])-Date.new(start[0],start[1],start[2])).to_i %>
        <h2 id="number"><%= duration %></h2>
        <p>days</p>
      </div>
    </div>
    <div id="days">
      <div class="dates">
        <p>Starts</p>
        <p><%= challenge.start_date %></p>
      </div>
      <div class="dates">
        <p>Ends</p>
        <p><%= challenge.end_date %></p>
      </div>
      <%= link_to "GO",challenge_path(challenge), class:"go" %>
    </div>
  </div>
</div>

app/views/challenges/_evidence.html.erb
<div class="card-trip">
  <div class="card-trip-infos">
    <div class="infos-text">
      <h2><%= link_to "#{session.activity}", exercise_session_path(session), class:"show-session" %></h2>
      <h3><%= session.time_length %> mins</h3>
    </div>
    <%= cl_image_tag session.challenge_info.user.photo.key, class:"card-trip-user avatar-bordered"%>
  </div>
  <%= cl_image_tag session.photo.key, class:"img-evidence"%>
</div>

app/views/challenges/_index-card.html.erb
<div class="card-product">
  <img src="https://i.pinimg.com/564x/63/ae/d8/63aed8ae9387568fe75ca014b09e72fe.jpg" />
  <div class="card-product-infos">
    <div class="name">
      <h2>SURF CHALLENGE</h2>
    </div>
    <div class="info">
      <div class="attributes">
        <h3>Activity</h3>
        <h3>Status</h3>
      </div>
      <div class="duration">
        <h2 id="number">30</h2>
        <p>days</p>
      </div>
    </div>
    <div id="days">
      <div class="dates">
        <p>Starts</p>
        <p>2024-09-15</p>
      </div>
      <div class="dates">
        <p>Ends</p>
        <p>2024-10-15 </p>
      </div>
    </div>
</div>
</div>

app/views/challenges/card-challenge-show.html.erb
<div class="card-challenge">
  <div class="card-challenge-infos">
    <div class="card-challenge-title">
      <h2 class="card-challenge-name"><%= @challenge.name %></h2>
    </div>
    <div class="card-challenge-info">
      <div class="card-challenge-attributes">
        <h3><%= @challenge.activity %></h3>
      </div>
      <div class="card-challenge-duration">
        <% final = @challenge.end_date.split("-").map(&:to_i) %>
        <% start = @challenge.start_date.split("-").map(&:to_i) %>
        <% duration = (Date.new(final[0],final[1],final[2])-Date.new(start[0],start[1],start[2])).to_i %>
        <h2 id="card-challenge-number"><%= duration %></h2>
        <p>days</p>
      </div>
    </div>
    <div id="card-challenge-days">
      <div class="card-challenge-dates">
        <p>Starts</p>
        <p><%= @challenge.start_date %></p>
      </div>
      <div class="card-challenge-dates">
        <p>Ends</p>
        <p><%= @challenge.end_date %></p>
      </div>
      <%= button_to "Delete Challenge", @challenge, class: "btn btn-outline-danger", method: :delete if policy(@challenge).destroy? %>
    </div>
  </div>
</div>

app/views/challenges/index.html.erb
<div>
  <div>
    <div data-controller="search-challenges" id="challenge-index">
      <h1>Challenges</h1>
      <%= render "shared/list", challenges: @challenge %>
      <div id="search-and-create" class="d-flex flex-column">
        <div id="search">
          <%= render "shared/search" %>
        </div>
        <div id="create-card-container">
          <%= render "challenge-card" %>
        </div>
      </div>
    </div>
    <div id="evidence-rand" >
      <div>
        <h1 style="height: auto;">Buddies in action</h1>
      </div>
      <div id="evidence-display">

        <% @exercise_sessions.each do |session| %>
          <%= render "evidence", session: session %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/challenges/new.html.erb
<div class="container p-4 d-flex justify-content-center">
  <div class="shadow-lg border border-light">
    <div class="m-3">
      <h2>Create your own challenge!</h2>
      <%= simple_form_for @challenge do |f| %>
        <%= f.input :name, prompt: "Challenge Name"%>
        <%= f.input :challenge_type, collection: Challenge::TYPES, prompt: "Select privacy setting" %>
        <%= f.input :activity, collection: Challenge::ACTIVITIES, prompt: "Select an activity" %>
        <%= f.input :status, as: :hidden, input_html: { value: "created" } %>
        <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>
        <%= f.input :start_date, as: :string, input_html: {data: {controller: "datepicker"}}%>
        <%= f.input :end_date, as: :string, input_html: {data: {controller: "datepicker"}}%>
        <%= f.button :submit, "Create challenge", class: "btn btn-warning" %>

      <% end %>
    </div>
  </div>
</div>

app/views/challenges/show.html.erb
<div class="challenge-display">
  <div class="challenge-display-cards d-flex justify-content-between">
    <div class="section-one">
      <div id="challenge-name">
        <h1><%= @challenge.name %></h1>
      </div>
        <div>
          <%= render "card" %>
        </div>
        <div>
          <%= render "buddies-card" %>
      </div>
    </div>
    <div class="section-two">
      <div class="background-section">
      <% if @cuser_evidence.nil? %>
        <div class="info-session">
          <h3>No Activity Yet</h3>
        </div>
        <% else %>
        <div class="info-session">
          <h3><%= @cuser_evidence.activity %></h3>
          <p><%= @cuser_evidence.time_length%> mins</p>
        </div>
        <%= cl_image_tag @cuser_evidence.photo.key, class:"img-section-evidence"%>
      <% end %>
      </div>
    </div>
  </div>

  <div class="challene-signs">
    <div class="card card-custom">
      <div class="card-body">
        <p>Invite your friends to join this challenge!</p>
        <%= simple_form_for [@challenge, @invite], html: { class: 'form-inline' } do |f| %>
          <div class="row">
            <div class="col-md-8">
              <%= f.input :invitee_id,
                          collection: User.where.not(id: @challenge.users.select(:id)).map { |user| [user.nickname, user.id] },
                          label: false,
                          include_blank: 'Select a buddy',
                          input_html: { class: 'form-control' } %>
            </div>
            <div class="col-md-4 text-md-right">
              <%= f.button :submit, "Invite your buddy", class: "btn btn-warning" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="card card-evidence">
      <div class="card-body d-flex justify-content-between align-items-center">
        <div>
          <h5 class="card-title mb-0">
            Your friends are <span class="card-title-yellow">working out</span>, what are <span class="card-title-yellow">you</span> doing?
          </h5>
        </div>
        <div class="d-flex align-items-center">
          <p class="evidence-text2">Add <span class="card-title-yellow">Today's</span> evidence!</p>
          <%= link_to "+", new_challenge_info_exercise_session_path(@user_challenge_info), class: "round-buton btn-evidence" %>
        </div>
      </div>
    </div>
  </div>

  <div id="evidence-rand" >
      <div>
        <h1 style="height: auto;">Buddies Today</h1>
      </div>
      <div id="evidence-display">
        <% @exercise_sessions.each do |session| %>
          <%= render "challenge-evidence", session: session %>
        <% end %>

      </div>
    </div>


</div>